# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: Publish to Modrinth (only on releases)
        if: startsWith(github.ref, 'refs/tags/')
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ env.PROJECT_ID }}
          loaders: fabric
          files: build/libs/su-craftable-name-tag-*.jar
          version: ${{ github.ref_name }}
          changelog: |
            ## SU Craftable Name Tag Mod ${{ github.ref_name }}
            
            ### What's New
            - Initial release
            - Adds craftable name tags using string, paper, and iron ingots
            - Compatible with Minecraft 1.21.6 and Fabric
            
            ### Recipe
            Craft name tags using:
            - 3 String
            - 1 Paper  
            - 2 Iron Ingot
          game-versions: |-
            1.21.x
